// <auto-generated />
using System;
using ElsaMina.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElsaMina.DataAccess.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20251231014720_ReworkUsers")]
    partial class ReworkUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElsaMina.DataAccess.Models.AddedCommand", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("AddedCommands");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.ArcadeLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ArcadeLevels");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.Badge", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsTeamTournament")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrophy")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SavedRoomId")
                        .HasColumnType("text");

                    b.HasKey("Id", "RoomId");

                    b.HasIndex("SavedRoomId");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.BadgeHolding", b =>
                {
                    b.Property<string>("BadgeId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.HasKey("BadgeId", "UserId", "RoomId");

                    b.HasIndex("BadgeId", "RoomId");

                    b.HasIndex("UserId", "RoomId");

                    b.ToTable("BadgeHoldings");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.RoomBotParameterValue", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<string>("ParameterId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("RoomId", "ParameterId");

                    b.ToTable("RoomBotParameterValues");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.RoomTeam", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.HasKey("TeamId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomTeams");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.RoomUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("JoinPhrase")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("PlayTime")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id", "RoomId");

                    b.ToTable("RoomUsers");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.SavedPoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<string>("SavedRoomId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SavedRoomId");

                    b.ToTable("SavedPolls");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.SavedRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.SavedUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastOnline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSeenRoomId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("TeamJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.TournamentRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<int>("PlayedGames")
                        .HasColumnType("integer");

                    b.Property<int>("RunnerUpCount")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentsEnteredCount")
                        .HasColumnType("integer");

                    b.Property<int>("WinsCount")
                        .HasColumnType("integer");

                    b.Property<int>("WonGames")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoomId");

                    b.ToTable("TournamentRecords");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.AddedCommand", b =>
                {
                    b.HasOne("ElsaMina.DataAccess.Models.SavedRoom", "SavedRoom")
                        .WithMany("AddedCommands")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedRoom");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.Badge", b =>
                {
                    b.HasOne("ElsaMina.DataAccess.Models.SavedRoom", null)
                        .WithMany("Badges")
                        .HasForeignKey("SavedRoomId");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.BadgeHolding", b =>
                {
                    b.HasOne("ElsaMina.DataAccess.Models.Badge", "Badge")
                        .WithMany("BadgeHolders")
                        .HasForeignKey("BadgeId", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElsaMina.DataAccess.Models.RoomUser", "RoomUser")
                        .WithMany("Badges")
                        .HasForeignKey("UserId", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("RoomUser");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.RoomBotParameterValue", b =>
                {
                    b.HasOne("ElsaMina.DataAccess.Models.SavedRoom", "SavedRoom")
                        .WithMany("ParameterValues")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedRoom");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.RoomTeam", b =>
                {
                    b.HasOne("ElsaMina.DataAccess.Models.SavedRoom", "SavedRoom")
                        .WithMany("Teams")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElsaMina.DataAccess.Models.Team", "Team")
                        .WithMany("Rooms")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedRoom");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.RoomUser", b =>
                {
                    b.HasOne("ElsaMina.DataAccess.Models.SavedUser", "User")
                        .WithMany("RoomData")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.SavedPoll", b =>
                {
                    b.HasOne("ElsaMina.DataAccess.Models.SavedRoom", "SavedRoom")
                        .WithMany("PollHistory")
                        .HasForeignKey("SavedRoomId");

                    b.Navigation("SavedRoom");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.TournamentRecord", b =>
                {
                    b.HasOne("ElsaMina.DataAccess.Models.RoomUser", "RoomUser")
                        .WithOne("TournamentRecord")
                        .HasForeignKey("ElsaMina.DataAccess.Models.TournamentRecord", "UserId", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomUser");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.Badge", b =>
                {
                    b.Navigation("BadgeHolders");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.RoomUser", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("TournamentRecord");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.SavedRoom", b =>
                {
                    b.Navigation("AddedCommands");

                    b.Navigation("Badges");

                    b.Navigation("ParameterValues");

                    b.Navigation("PollHistory");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.SavedUser", b =>
                {
                    b.Navigation("RoomData");
                });

            modelBuilder.Entity("ElsaMina.DataAccess.Models.Team", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
