//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElsaMina.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fr_FR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr_FR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ElsaMina.Core.Resources.Resources_fr_FR", typeof(Resources_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        internal static string badge_help_message {
            get {
                return ResourceManager.GetString("badge_help_message", resourceCulture);
            }
        }
        
        internal static string badge_add_success_message {
            get {
                return ResourceManager.GetString("badge_add_success_message", resourceCulture);
            }
        }
        
        internal static string badge_add_failure_message {
            get {
                return ResourceManager.GetString("badge_add_failure_message", resourceCulture);
            }
        }
        
        internal static string addcommand_name_too_long {
            get {
                return ResourceManager.GetString("addcommand_name_too_long", resourceCulture);
            }
        }
        
        internal static string addcommand_content_too_long {
            get {
                return ResourceManager.GetString("addcommand_content_too_long", resourceCulture);
            }
        }
        
        internal static string addcommand_bad_first_char {
            get {
                return ResourceManager.GetString("addcommand_bad_first_char", resourceCulture);
            }
        }
        
        internal static string addcommand_already_exist {
            get {
                return ResourceManager.GetString("addcommand_already_exist", resourceCulture);
            }
        }
        
        internal static string addcommand_success {
            get {
                return ResourceManager.GetString("addcommand_success", resourceCulture);
            }
        }
        
        internal static string room_dashboard {
            get {
                return ResourceManager.GetString("room_dashboard", resourceCulture);
            }
        }
        
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        internal static string dashboard_room_doesnt_exist {
            get {
                return ResourceManager.GetString("dashboard_room_doesnt_exist", resourceCulture);
            }
        }
        
        internal static string dashboard_locale_name {
            get {
                return ResourceManager.GetString("dashboard_locale_name", resourceCulture);
            }
        }
        
        internal static string dashboard_locale_description {
            get {
                return ResourceManager.GetString("dashboard_locale_description", resourceCulture);
            }
        }
        
        internal static string dashboard_errors_name {
            get {
                return ResourceManager.GetString("dashboard_errors_name", resourceCulture);
            }
        }
        
        internal static string dashboard_errors_description {
            get {
                return ResourceManager.GetString("dashboard_errors_description", resourceCulture);
            }
        }
        
        internal static string dashboard_autocorrect_name {
            get {
                return ResourceManager.GetString("dashboard_autocorrect_name", resourceCulture);
            }
        }
        
        internal static string dashboard_autocorrect_description {
            get {
                return ResourceManager.GetString("dashboard_autocorrect_description", resourceCulture);
            }
        }
        
        internal static string room_config_success {
            get {
                return ResourceManager.GetString("room_config_success", resourceCulture);
            }
        }
        
        internal static string room_config_failure {
            get {
                return ResourceManager.GetString("room_config_failure", resourceCulture);
            }
        }
        
        internal static string room_config_room_not_found {
            get {
                return ResourceManager.GetString("room_config_room_not_found", resourceCulture);
            }
        }
        
        internal static string room_config_locale_not_found {
            get {
                return ResourceManager.GetString("room_config_locale_not_found", resourceCulture);
            }
        }
        
        internal static string editcommand_help {
            get {
                return ResourceManager.GetString("editcommand_help", resourceCulture);
            }
        }
        
        internal static string editcommand_success {
            get {
                return ResourceManager.GetString("editcommand_success", resourceCulture);
            }
        }
        
        internal static string editcommand_failure {
            get {
                return ResourceManager.GetString("editcommand_failure", resourceCulture);
            }
        }
        
        internal static string deletecommand_help {
            get {
                return ResourceManager.GetString("deletecommand_help", resourceCulture);
            }
        }
        
        internal static string deletecommand_failure {
            get {
                return ResourceManager.GetString("deletecommand_failure", resourceCulture);
            }
        }
        
        internal static string deletecommand_success {
            get {
                return ResourceManager.GetString("deletecommand_success", resourceCulture);
            }
        }
        
        internal static string badge_add_already_exist {
            get {
                return ResourceManager.GetString("badge_add_already_exist", resourceCulture);
            }
        }
        
        internal static string badge_give_help_message {
            get {
                return ResourceManager.GetString("badge_give_help_message", resourceCulture);
            }
        }
        
        internal static string badge_give_could_not_find_badge {
            get {
                return ResourceManager.GetString("badge_give_could_not_find_badge", resourceCulture);
            }
        }
        
        internal static string badge_give_error {
            get {
                return ResourceManager.GetString("badge_give_error", resourceCulture);
            }
        }
        
        internal static string badge_give_success {
            get {
                return ResourceManager.GetString("badge_give_success", resourceCulture);
            }
        }
        
        internal static string rank_owner {
            get {
                return ResourceManager.GetString("rank_owner", resourceCulture);
            }
        }
        
        internal static string rank_bot {
            get {
                return ResourceManager.GetString("rank_bot", resourceCulture);
            }
        }
        
        internal static string rank_mod {
            get {
                return ResourceManager.GetString("rank_mod", resourceCulture);
            }
        }
        
        internal static string rank_driver {
            get {
                return ResourceManager.GetString("rank_driver", resourceCulture);
            }
        }
        
        internal static string rank_prizewinner {
            get {
                return ResourceManager.GetString("rank_prizewinner", resourceCulture);
            }
        }
        
        internal static string rank_voice {
            get {
                return ResourceManager.GetString("rank_voice", resourceCulture);
            }
        }
        
        internal static string profile_status {
            get {
                return ResourceManager.GetString("profile_status", resourceCulture);
            }
        }
        
        internal static string rank_host {
            get {
                return ResourceManager.GetString("rank_host", resourceCulture);
            }
        }
        
        internal static string badge_delete_doesnt_exist {
            get {
                return ResourceManager.GetString("badge_delete_doesnt_exist", resourceCulture);
            }
        }
        
        internal static string badge_delete_success {
            get {
                return ResourceManager.GetString("badge_delete_success", resourceCulture);
            }
        }
        
        internal static string badge_delete_failure {
            get {
                return ResourceManager.GetString("badge_delete_failure", resourceCulture);
            }
        }
        
        internal static string takebadge_help_message {
            get {
                return ResourceManager.GetString("takebadge_help_message", resourceCulture);
            }
        }
        
        internal static string takebadge_success {
            get {
                return ResourceManager.GetString("takebadge_success", resourceCulture);
            }
        }
        
        internal static string takebadge_failure {
            get {
                return ResourceManager.GetString("takebadge_failure", resourceCulture);
            }
        }
        
        internal static string takebadge_badge_doesnt_exist {
            get {
                return ResourceManager.GetString("takebadge_badge_doesnt_exist", resourceCulture);
            }
        }
        
        internal static string avatar_help_message {
            get {
                return ResourceManager.GetString("avatar_help_message", resourceCulture);
            }
        }
        
        internal static string avatar_success {
            get {
                return ResourceManager.GetString("avatar_success", resourceCulture);
            }
        }
        
        internal static string avatar_failure {
            get {
                return ResourceManager.GetString("avatar_failure", resourceCulture);
            }
        }
        
        internal static string title_help_message {
            get {
                return ResourceManager.GetString("title_help_message", resourceCulture);
            }
        }
        
        internal static string title_success {
            get {
                return ResourceManager.GetString("title_success", resourceCulture);
            }
        }
        
        internal static string title_failure {
            get {
                return ResourceManager.GetString("title_failure", resourceCulture);
            }
        }
        
        internal static string profile_no_title {
            get {
                return ResourceManager.GetString("profile_no_title", resourceCulture);
            }
        }
        
        internal static string profile_no_badge {
            get {
                return ResourceManager.GetString("profile_no_badge", resourceCulture);
            }
        }
        
        internal static string allcommands_alias {
            get {
                return ResourceManager.GetString("allcommands_alias", resourceCulture);
            }
        }
        
        internal static string allcommands_allowed_in_pm {
            get {
                return ResourceManager.GetString("allcommands_allowed_in_pm", resourceCulture);
            }
        }
        
        internal static string allcommands_wl_only {
            get {
                return ResourceManager.GetString("allcommands_wl_only", resourceCulture);
            }
        }
        
        internal static string allcommands_pm_only {
            get {
                return ResourceManager.GetString("allcommands_pm_only", resourceCulture);
            }
        }
        
        internal static string allcommands_required_rank {
            get {
                return ResourceManager.GetString("allcommands_required_rank", resourceCulture);
            }
        }
        
        internal static string profile_register_date {
            get {
                return ResourceManager.GetString("profile_register_date", resourceCulture);
            }
        }
        
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        internal static string guessing_game_game_ended {
            get {
                return ResourceManager.GetString("guessing_game_game_ended", resourceCulture);
            }
        }
        
        internal static string guessing_game_point {
            get {
                return ResourceManager.GetString("guessing_game_point", resourceCulture);
            }
        }
        
        internal static string guessing_game_final_scores {
            get {
                return ResourceManager.GetString("guessing_game_final_scores", resourceCulture);
            }
        }
        
        internal static string guessing_game_turn_count {
            get {
                return ResourceManager.GetString("guessing_game_turn_count", resourceCulture);
            }
        }
        
        internal static string guessing_game_answer_not_found {
            get {
                return ResourceManager.GetString("guessing_game_answer_not_found", resourceCulture);
            }
        }
        
        internal static string guessing_game_round_won {
            get {
                return ResourceManager.GetString("guessing_game_round_won", resourceCulture);
            }
        }
        
        internal static string guessing_game_result_ended {
            get {
                return ResourceManager.GetString("guessing_game_result_ended", resourceCulture);
            }
        }
        
        internal static string countries_game_start {
            get {
                return ResourceManager.GetString("countries_game_start", resourceCulture);
            }
        }
        
        internal static string end_guessing_game_no_game {
            get {
                return ResourceManager.GetString("end_guessing_game_no_game", resourceCulture);
            }
        }
        
        internal static string end_guessing_game_success {
            get {
                return ResourceManager.GetString("end_guessing_game_success", resourceCulture);
            }
        }
        
        internal static string team_preview_author {
            get {
                return ResourceManager.GetString("team_preview_author", resourceCulture);
            }
        }
        
        internal static string team_preview_title {
            get {
                return ResourceManager.GetString("team_preview_title", resourceCulture);
            }
        }
        
        internal static string team_preview_click_icons {
            get {
                return ResourceManager.GetString("team_preview_click_icons", resourceCulture);
            }
        }
        
        internal static string dashboard_team_previews_name {
            get {
                return ResourceManager.GetString("dashboard_team_previews_name", resourceCulture);
            }
        }
        
        internal static string dashboard_team_previews_description {
            get {
                return ResourceManager.GetString("dashboard_team_previews_description", resourceCulture);
            }
        }
        
        internal static string add_team_help_message {
            get {
                return ResourceManager.GetString("add_team_help_message", resourceCulture);
            }
        }
        
        internal static string add_team_name_too_long {
            get {
                return ResourceManager.GetString("add_team_name_too_long", resourceCulture);
            }
        }
        
        internal static string add_team_no_provider {
            get {
                return ResourceManager.GetString("add_team_no_provider", resourceCulture);
            }
        }
        
        internal static string add_team_no_export_error {
            get {
                return ResourceManager.GetString("add_team_no_export_error", resourceCulture);
            }
        }
        
        internal static string add_team_success {
            get {
                return ResourceManager.GetString("add_team_success", resourceCulture);
            }
        }
        
        internal static string add_team_failure {
            get {
                return ResourceManager.GetString("add_team_failure", resourceCulture);
            }
        }
        
        internal static string add_team_to_room_no_arg {
            get {
                return ResourceManager.GetString("add_team_to_room_no_arg", resourceCulture);
            }
        }
        
        internal static string add_team_to_room_no_team {
            get {
                return ResourceManager.GetString("add_team_to_room_no_team", resourceCulture);
            }
        }
        
        internal static string add_team_to_room_team_already_in_room {
            get {
                return ResourceManager.GetString("add_team_to_room_team_already_in_room", resourceCulture);
            }
        }
        
        internal static string add_team_to_room_success {
            get {
                return ResourceManager.GetString("add_team_to_room_success", resourceCulture);
            }
        }
        
        internal static string add_team_to_room_failure {
            get {
                return ResourceManager.GetString("add_team_to_room_failure", resourceCulture);
            }
        }
        
        internal static string sample_team_description {
            get {
                return ResourceManager.GetString("sample_team_description", resourceCulture);
            }
        }
        
        internal static string sample_team_info {
            get {
                return ResourceManager.GetString("sample_team_info", resourceCulture);
            }
        }
        
        internal static string deleteteam_team_not_found {
            get {
                return ResourceManager.GetString("deleteteam_team_not_found", resourceCulture);
            }
        }
        
        internal static string deleteteam_team_deleted_successfully {
            get {
                return ResourceManager.GetString("deleteteam_team_deleted_successfully", resourceCulture);
            }
        }
        
        internal static string deleteteam_team_deletion_error {
            get {
                return ResourceManager.GetString("deleteteam_team_deletion_error", resourceCulture);
            }
        }
        
        internal static string team_showcase_not_found {
            get {
                return ResourceManager.GetString("team_showcase_not_found", resourceCulture);
            }
        }
        
        internal static string aboutrepeat_not_found {
            get {
                return ResourceManager.GetString("aboutrepeat_not_found", resourceCulture);
            }
        }
        
        internal static string aboutrepeat_helpmessage {
            get {
                return ResourceManager.GetString("aboutrepeat_helpmessage", resourceCulture);
            }
        }
        
        internal static string parameter_name_locale {
            get {
                return ResourceManager.GetString("parameter_name_locale", resourceCulture);
            }
        }
        
        internal static string parameter_name_is_showing_team_links_preview {
            get {
                return ResourceManager.GetString("parameter_name_is_showing_team_links_preview", resourceCulture);
            }
        }
        
        internal static string parameter_name_is_showing_error_messages {
            get {
                return ResourceManager.GetString("parameter_name_is_showing_error_messages", resourceCulture);
            }
        }
        
        internal static string parameter_name_has_command_auto_correct {
            get {
                return ResourceManager.GetString("parameter_name_has_command_auto_correct", resourceCulture);
            }
        }
        
        internal static string parameter_description_has_command_auto_correct {
            get {
                return ResourceManager.GetString("parameter_description_has_command_auto_correct", resourceCulture);
            }
        }
        
        internal static string parameter_description_is_showing_error_messages {
            get {
                return ResourceManager.GetString("parameter_description_is_showing_error_messages", resourceCulture);
            }
        }
        
        internal static string parameter_description_is_showing_team_links_preview {
            get {
                return ResourceManager.GetString("parameter_description_is_showing_team_links_preview", resourceCulture);
            }
        }
        
        internal static string parameter_description_locale {
            get {
                return ResourceManager.GetString("parameter_description_locale", resourceCulture);
            }
        }
        
        internal static string c4_game_name {
            get {
                return ResourceManager.GetString("c4_game_name", resourceCulture);
            }
        }
        
        internal static string c4_game_rules {
            get {
                return ResourceManager.GetString("c4_game_rules", resourceCulture);
            }
        }
        
        internal static string c4_game_current_turn {
            get {
                return ResourceManager.GetString("c4_game_current_turn", resourceCulture);
            }
        }
        
        internal static string c4_game_how_to_play {
            get {
                return ResourceManager.GetString("c4_game_how_to_play", resourceCulture);
            }
        }
        
        internal static string c4_game_timeout {
            get {
                return ResourceManager.GetString("c4_game_timeout", resourceCulture);
            }
        }
        
        internal static string c4_game_players {
            get {
                return ResourceManager.GetString("c4_game_players", resourceCulture);
            }
        }
        
        internal static string vs {
            get {
                return ResourceManager.GetString("vs", resourceCulture);
            }
        }
        
        internal static string c4_game_turn {
            get {
                return ResourceManager.GetString("c4_game_turn", resourceCulture);
            }
        }
        
        internal static string c4_game_party_id {
            get {
                return ResourceManager.GetString("c4_game_party_id", resourceCulture);
            }
        }
        
        internal static string c4_game_tie_end {
            get {
                return ResourceManager.GetString("c4_game_tie_end", resourceCulture);
            }
        }
        
        internal static string c4_game_win_message {
            get {
                return ResourceManager.GetString("c4_game_win_message", resourceCulture);
            }
        }
        
        internal static string team_list_empty {
            get {
                return ResourceManager.GetString("team_list_empty", resourceCulture);
            }
        }
        
        internal static string name_color_help {
            get {
                return ResourceManager.GetString("name_color_help", resourceCulture);
            }
        }
        
        internal static string setjoinphrase_help_message {
            get {
                return ResourceManager.GetString("setjoinphrase_help_message", resourceCulture);
            }
        }
        
        internal static string setjoinphrase_success {
            get {
                return ResourceManager.GetString("setjoinphrase_success", resourceCulture);
            }
        }
        
        internal static string setjoinphrase_failure {
            get {
                return ResourceManager.GetString("setjoinphrase_failure", resourceCulture);
            }
        }
        
        internal static string replay_preview_watch {
            get {
                return ResourceManager.GetString("replay_preview_watch", resourceCulture);
            }
        }
        
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        internal static string views {
            get {
                return ResourceManager.GetString("views", resourceCulture);
            }
        }
        
        internal static string rating {
            get {
                return ResourceManager.GetString("rating", resourceCulture);
            }
        }
        
        internal static string parameter_name_is_showing_replays_preview {
            get {
                return ResourceManager.GetString("parameter_name_is_showing_replays_preview", resourceCulture);
            }
        }
        
        internal static string parameter_description_is_showing_replays_preview {
            get {
                return ResourceManager.GetString("parameter_description_is_showing_replays_preview", resourceCulture);
            }
        }
    }
}
