//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElsaMina.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElsaMina.Core.Resources.Resources.en-US", typeof(Resources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command already exist..
        /// </summary>
        internal static string addcommand_already_exist {
            get {
                return ResourceManager.GetString("addcommand_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command&apos;s content cannot start with this character..
        /// </summary>
        internal static string addcommand_bad_first_char {
            get {
                return ResourceManager.GetString("addcommand_bad_first_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command content is too long..
        /// </summary>
        internal static string addcommand_content_too_long {
            get {
                return ResourceManager.GetString("addcommand_content_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name is too long..
        /// </summary>
        internal static string addcommand_name_too_long {
            get {
                return ResourceManager.GetString("addcommand_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added new command : **{0}**..
        /// </summary>
        internal static string addcommand_success {
            get {
                return ResourceManager.GetString("addcommand_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        internal static string allcommands_alias {
            get {
                return ResourceManager.GetString("allcommands_alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed in PM.
        /// </summary>
        internal static string allcommands_allowed_in_pm {
            get {
                return ResourceManager.GetString("allcommands_allowed_in_pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Only.
        /// </summary>
        internal static string allcommands_pm_only {
            get {
                return ResourceManager.GetString("allcommands_pm_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required rank.
        /// </summary>
        internal static string allcommands_required_rank {
            get {
                return ResourceManager.GetString("allcommands_required_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitelist Only.
        /// </summary>
        internal static string allcommands_wl_only {
            get {
                return ResourceManager.GetString("allcommands_wl_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating an avatar : {0}.
        /// </summary>
        internal static string avatar_failure {
            get {
                return ResourceManager.GetString("avatar_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates a user&apos;s avatar.  Syntax : -avarar &lt;user&gt;, &lt;avatar URL&gt;.
        /// </summary>
        internal static string avatar_help_message {
            get {
                return ResourceManager.GetString("avatar_help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s avatar has been updated..
        /// </summary>
        internal static string avatar_success {
            get {
                return ResourceManager.GetString("avatar_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The badge {0} already exist..
        /// </summary>
        internal static string badge_add_already_exist {
            get {
                return ResourceManager.GetString("badge_add_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding the badge : {0}.
        /// </summary>
        internal static string badge_add_failure_message {
            get {
                return ResourceManager.GetString("badge_add_failure_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New badge added successfully..
        /// </summary>
        internal static string badge_add_success_message {
            get {
                return ResourceManager.GetString("badge_add_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; badge doesn&apos;t exist..
        /// </summary>
        internal static string badge_delete_doesnt_exist {
            get {
                return ResourceManager.GetString("badge_delete_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting badge : {0}.
        /// </summary>
        internal static string badge_delete_failure {
            get {
                return ResourceManager.GetString("badge_delete_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The badge &quot;{0}&quot; has been removed..
        /// </summary>
        internal static string badge_delete_success {
            get {
                return ResourceManager.GetString("badge_delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find badge {0}..
        /// </summary>
        internal static string badge_give_could_not_find_badge {
            get {
                return ResourceManager.GetString("badge_give_could_not_find_badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while giving the badge : {0}.
        /// </summary>
        internal static string badge_give_error {
            get {
                return ResourceManager.GetString("badge_give_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives a badge to someone. Syntax : -givebadge &lt;user&gt;, &lt;badge&gt;.
        /// </summary>
        internal static string badge_give_help_message {
            get {
                return ResourceManager.GetString("badge_give_help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; received the badge &quot;{1}&quot;..
        /// </summary>
        internal static string badge_give_success {
            get {
                return ResourceManager.GetString("badge_give_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new badge. Syntax : -add-badge &lt;name&gt;, &lt;image&gt;. Use -add-trophy to add a trophy..
        /// </summary>
        internal static string badge_help_message {
            get {
                return ResourceManager.GetString("badge_help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A countriesgame started! Reply with the name of the country directly in the chat..
        /// </summary>
        internal static string countries_game_start {
            get {
                return ResourceManager.GetString("countries_game_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows suggested commands when someone tries to use a command that doesn&apos;t exist..
        /// </summary>
        internal static string dashboard_autocorrect_description {
            get {
                return ResourceManager.GetString("dashboard_autocorrect_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show command suggestions.
        /// </summary>
        internal static string dashboard_autocorrect_name {
            get {
                return ResourceManager.GetString("dashboard_autocorrect_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the stacktrace of a command that crashed..
        /// </summary>
        internal static string dashboard_errors_description {
            get {
                return ResourceManager.GetString("dashboard_errors_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show commands errors.
        /// </summary>
        internal static string dashboard_errors_name {
            get {
                return ResourceManager.GetString("dashboard_errors_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The locale used by the bot in this room..
        /// </summary>
        internal static string dashboard_locale_description {
            get {
                return ResourceManager.GetString("dashboard_locale_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        internal static string dashboard_locale_name {
            get {
                return ResourceManager.GetString("dashboard_locale_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room {0} not found..
        /// </summary>
        internal static string dashboard_room_doesnt_exist {
            get {
                return ResourceManager.GetString("dashboard_room_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete command : {0}.
        /// </summary>
        internal static string deletecommand_failure {
            get {
                return ResourceManager.GetString("deletecommand_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes an added command. Syntax : -deletecommand &lt;command&gt;.
        /// </summary>
        internal static string deletecommand_help {
            get {
                return ResourceManager.GetString("deletecommand_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command {0} has been deleted.
        /// </summary>
        internal static string deletecommand_success {
            get {
                return ResourceManager.GetString("deletecommand_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update command : {0}.
        /// </summary>
        internal static string editcommand_failure {
            get {
                return ResourceManager.GetString("editcommand_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edits an added command. Syntax : -editcommand &lt;name&gt;, &lt;content&gt;.
        /// </summary>
        internal static string editcommand_help {
            get {
                return ResourceManager.GetString("editcommand_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command {0} has been updated.
        /// </summary>
        internal static string editcommand_success {
            get {
                return ResourceManager.GetString("editcommand_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no game currently running in this room..
        /// </summary>
        internal static string end_guessing_game_no_game {
            get {
                return ResourceManager.GetString("end_guessing_game_no_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended..
        /// </summary>
        internal static string end_guessing_game_success {
            get {
                return ResourceManager.GetString("end_guessing_game_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one found the answer in time! The answer was: {0}.
        /// </summary>
        internal static string guessing_game_answer_not_found {
            get {
                return ResourceManager.GetString("guessing_game_answer_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final scores.
        /// </summary>
        internal static string guessing_game_final_scores {
            get {
                return ResourceManager.GetString("guessing_game_final_scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is up! The answer was : {0}.
        /// </summary>
        internal static string guessing_game_game_ended {
            get {
                return ResourceManager.GetString("guessing_game_game_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string guessing_game_point {
            get {
                return ResourceManager.GetString("guessing_game_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is over!.
        /// </summary>
        internal static string guessing_game_result_ended {
            get {
                return ResourceManager.GetString("guessing_game_result_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wins this round ! They now have {1} point{2}.
        /// </summary>
        internal static string guessing_game_round_won {
            get {
                return ResourceManager.GetString("guessing_game_round_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn #{0}.
        /// </summary>
        internal static string guessing_game_turn_count {
            get {
                return ResourceManager.GetString("guessing_game_turn_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elsa-Mina v7 : Bot in development.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No badge.
        /// </summary>
        internal static string profile_no_badge {
            get {
                return ResourceManager.GetString("profile_no_badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title.
        /// </summary>
        internal static string profile_no_title {
            get {
                return ResourceManager.GetString("profile_no_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        internal static string profile_register_date {
            get {
                return ResourceManager.GetString("profile_register_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string profile_status {
            get {
                return ResourceManager.GetString("profile_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        internal static string rank_bot {
            get {
                return ResourceManager.GetString("rank_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string rank_driver {
            get {
                return ResourceManager.GetString("rank_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string rank_host {
            get {
                return ResourceManager.GetString("rank_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string rank_mod {
            get {
                return ResourceManager.GetString("rank_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Owner.
        /// </summary>
        internal static string rank_owner {
            get {
                return ResourceManager.GetString("rank_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize Winner.
        /// </summary>
        internal static string rank_prizewinner {
            get {
                return ResourceManager.GetString("rank_prizewinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        internal static string rank_voice {
            get {
                return ResourceManager.GetString("rank_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while updating the configuration : {0}.
        /// </summary>
        internal static string room_config_failure {
            get {
                return ResourceManager.GetString("room_config_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find locale &apos;{0}&apos;.
        /// </summary>
        internal static string room_config_locale_not_found {
            get {
                return ResourceManager.GetString("room_config_locale_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find room &apos;{0}&apos;.
        /// </summary>
        internal static string room_config_room_not_found {
            get {
                return ResourceManager.GetString("room_config_room_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration of room {0} has been updated..
        /// </summary>
        internal static string room_config_success {
            get {
                return ResourceManager.GetString("room_config_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s dashboard.
        /// </summary>
        internal static string room_dashboard {
            get {
                return ResourceManager.GetString("room_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; doesn&apos;t have badge &quot;{1}&quot; .
        /// </summary>
        internal static string takebadge_badge_doesnt_exist {
            get {
                return ResourceManager.GetString("takebadge_badge_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while taking the badge : {0}.
        /// </summary>
        internal static string takebadge_failure {
            get {
                return ResourceManager.GetString("takebadge_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a user&apos;s badge. Syntax : -takebadge &lt;user&gt;, &lt;badge&gt;.
        /// </summary>
        internal static string takebadge_help_message {
            get {
                return ResourceManager.GetString("takebadge_help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;{0}&quot; no longer has the badge &quot;{1}&quot;..
        /// </summary>
        internal static string takebadge_success {
            get {
                return ResourceManager.GetString("takebadge_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Created by {0}).
        /// </summary>
        internal static string team_preview_author {
            get {
                return ResourceManager.GetString("team_preview_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the icons to display the importable version.
        /// </summary>
        internal static string team_preview_click_icons {
            get {
                return ResourceManager.GetString("team_preview_click_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s team.
        /// </summary>
        internal static string team_preview_title {
            get {
                return ResourceManager.GetString("team_preview_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the title : {0}.
        /// </summary>
        internal static string title_failure {
            get {
                return ResourceManager.GetString("title_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates a user&apos;s title. Syntax : -title &lt;user&gt;, &lt;title&gt;.
        /// </summary>
        internal static string title_help_message {
            get {
                return ResourceManager.GetString("title_help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s title has been updated..
        /// </summary>
        internal static string title_success {
            get {
                return ResourceManager.GetString("title_success", resourceCulture);
            }
        }
    }
}
