//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElsaMina.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElsaMina.Core.Resources.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande existe déjà..
        /// </summary>
        internal static string addcommand_already_exist {
            get {
                return ResourceManager.GetString("addcommand_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le contenu de la commande ne peut pas débuter par ce caractère..
        /// </summary>
        internal static string addcommand_bad_first_char {
            get {
                return ResourceManager.GetString("addcommand_bad_first_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le contenu de la commande est trop long..
        /// </summary>
        internal static string addcommand_content_too_long {
            get {
                return ResourceManager.GetString("addcommand_content_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de la commande est trop long..
        /// </summary>
        internal static string addcommand_name_too_long {
            get {
                return ResourceManager.GetString("addcommand_name_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande **{0}** a été ajoutée avec succès..
        /// </summary>
        internal static string addcommand_success {
            get {
                return ResourceManager.GetString("addcommand_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue en ajoutant le badge : {0}.
        /// </summary>
        internal static string badge_add_failure_message {
            get {
                return ResourceManager.GetString("badge_add_failure_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge ajouté avec succès..
        /// </summary>
        internal static string badge_add_success_message {
            get {
                return ResourceManager.GetString("badge_add_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajoute un nouveau badge. Syntaxe : -add-badge &lt;nom&gt;, &lt;image&gt;. Utiliser -add-trophy pour ajouter un trophée..
        /// </summary>
        internal static string badge_help_message {
            get {
                return ResourceManager.GetString("badge_help_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elsa-Mina v7 : Bot en développement.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
    }
}
