name: pr

on:
  pull_request:
    branches: ["master"]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      dotnet-version: "8.0.x"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
