name: test

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: restore
        run: ./scripts/restore.sh
      - name: test
        continue-on-error: true
        run: ./scripts/test.sh
      - name: publish results
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: "**/test-results.trx"
          reporter: dotnet-trx
